# Generated by Django 5.0.1 on 2024-03-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Actor_1', models.CharField(max_length=50)),
                ('Actor_2', models.CharField(max_length=50)),
                ('Song_1', models.CharField(max_length=100)),
                ('Song_2', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=100)),
            ],
        ),
    ]
